version: '3'

services:
  db:
    build: ./mysql/
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql # データの永続化
      - ./mysql/sqls:/docker-entrypoint-initdb.d # 初期化時に実行するSQL
    environment:
      MYSQL_ROOT_PASSWORD: hoge # パスワードはお好みで
      DB_USER: root
      DB_PASSWORD: hoge
      MYSQL_DATABASE: flask_sample
      DB_HOST: ${DB_HOST}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
  flask:
    build: .
    ports:
      - 5000:80
    volumes:
      - ./app:/app
    links:
      - db